1.

A:
select DONOR.FIRSTNAME, DONOR.LASTNAME, PLEDGE.PLEDGEAMT, PLEDGE.PLEDGEDATE, PLEDGE.IDDONOR
from DD_DONOR DONOR, DD_PLEDGE PLEDGE
where DONOR.IDDONOR = PLEDGE.IDDONOR;

B:
select DONOR.FIRSTNAME, DONOR.LASTNAME, PLEDGE.PLEDGEAMT, PLEDGE.PLEDGEDATE, PLEDGE.IDDONOR, PAYMENT.PAYAMT
from DD_DONOR DONOR, DD_PLEDGE PLEDGE, DD_PAYMENT PAYMENT
where DONOR.IDDONOR = PLEDGE.IDDONOR 
and PLEDGE.IDPLEDGE = PAYMENT.IDPLEDGE;

C:
select PROJECT.PROJNAME, PLEDGE.IDPROJ, PLEDGE.IDPLEDGE
from DD_PROJECT PROJECT, DD_PLEDGE PLEDGE
where PROJECT.IDPROJ = PLEDGE.IDPROJ;

D:
select d.idDonor, d.Firstname, d.Lastname, count(*) count
from DD_Donor d
join DD_Pledge p
on d.idDonor=p.idDonor
group by (d.idDonor, d.Firstname, d.Lastname)

E:
select *
from DD_PLEDGE
where PLEDGEDATE < '08-MAR-12';

2.

A:

